### ISSUE TITLE
"Exception of type 'UnityEngine.ExitGUIException' was thrown." error happens whenever you click the circle next to a reference

### ISSUE THREAD

**Issue by Phasedragon** [orels1/UdonToolkit#48]
Doesn't seem to break anything whatsoever, but worth mentioning

![image](https://user-images.githubusercontent.com/24859894/93089006-886e4a00-f64f-11ea-95d6-93fe68abacb9.png)

Error leads to line 325 of UTEditor.cs

![image](https://user-images.githubusercontent.com/24859894/93089135-b94e7f00-f64f-11ea-890f-5ff98ce29fb4.png)

**Comment by orels1** [comment]
Intresting, not really sure what can be happening here, considering i just draw a regular field 🤔 but i'll take a look, might be a wontfix tho

**Comment by orels1** [comment]
So i added a try-catch to the gui code to fallback to the default editor instead of fully crashing and stuff, but for some reason - Unity throws an ExitGUI exception when you click on the circle thing, while it hides it when you don't have a try-catch. Aded a check that just silences the ExitGUI as there is seemingly no harm in that, maybe will look into the root of the issue down the line.

Fixed in develop
Here's a package: 
[UdonToolkit_v0.4.2.zip](https://github.com/orels1/UdonToolkit/files/5221584/UdonToolkit_v0.4.2.zip)
